export const unlimitedApps = [
    {
        id: '001',
        name: 'Whatsapp',
        icon: './assets/icons/Whatsapp.png',
        style: '',
    },
    {
        id: '002',
        name: 'Telegram',
        icon: './assets/icons/telegram.png',
        style: '',
    },
    {
        id: '003',
        name: 'Instagram',
        icon: './assets/icons/Instagram.png',
        style: '',
    },
    {
        id: '004',
        name: 'Facebook',
        icon: './assets/icons/Facebook.png',
        style: '',
    },
    {
        id: '005',
        name: 'Messenger',
        icon: './assets/icons/Facebook-messenger.png',
        style: '',
    },
    {
        id: '006',
        name: 'Twitter',
        icon: './assets/icons/Twitter.png',
        style: '',
    },
    {
        id: '007',
        name: 'Waze',
        icon: './assets/icons/🦆 icon _waze_.png',
        style: '',
    },
    {
        id: '008',
        name: 'Cabify',
        icon: './assets/icons/6b263b5cfca33904cd740d5a7847a92d-removebg-preview 1.png',
        style: '',
    },
    {
        id: '009',
        name: 'Easy Taxi',
        icon: './assets/icons/416wpuP3WDL 1.png',
        style: '',
    },
    {
        id: '010',
        name: 'Moovit',
        icon: './assets/icons/apps.6701.9007199266249165 1.png',
        style: '',
    },
    {
        id: '011',
        name: 'Tiktok',
        icon: './assets/icons/🦆 icon _tiktok_.png',
        style: '',
    },
    {
        id: '012',
        name: 'Netflix',
        icon: './assets/icons/🦆 icon _netflix_.png',
        style: '',
    },
    {
        id: '013',
        name: 'Youtube',
        icon: './assets/icons/Youtube.png',
        style: '',
    },
    {
        id: '014',
        name: 'Claro Música',
        icon: './assets/icons/unnamed-removebg-preview 1.png',
        style: '',
    },
];
