export {default as SearchBar} from './SearchBar';
export {default as SimplePlansCard} from './SimplePlansCard';
export {default as Form} from './Form';
export {default as SimplePlans} from './SimplePlans';
export {default as AddNewPlan} from './AddNewPlan';
export {default as Operadoras} from './Operadoras';
export {default as NewPlanInputs} from './NewPlanInputs';
export {default as UnlimitedApps} from './UnlimitedApps';
export {default as NewPlanFinalInputs} from './NewPlanFinalInputs';
export {default as Cityes} from './Cityes';
export {default as CompletePlansCard} from './CompletePlansCard';
export {default as SeeMore} from './SeeMore';
export {default as ClientsCard} from './ClientsCard';
export {default as ArchivedPlansCard} from './ArchivedPlansCard';
export {default as Header} from './Header';
export {default as Benefits} from './Benefits';
export {default as Menu} from './Menu';
export {default as About} from './About';
export {default as SearchPlans} from './SearchPlans'
